Device set to use cpu
2025-01-29 10:40:12,960 [ERROR] An error occurred: No module named 'myproject'
Device set to use cpu
2025-01-29 07:46:13,965 [INFO] Django environment set up successfully.
2025-01-29 07:55:26,309 [INFO] Processed 224 records so far...
2025-01-29 07:55:32,201 [INFO] Email sent successfully with the CSV attachment.
2025-01-29 07:55:32,203 [INFO] Task completed: {"message": "Misused sender IDs have been processed and emailed successfully."}
Device set to use cpu
2025-01-29 10:17:12,188 [INFO] Django environment set up successfully.
2025-01-29 10:25:10,305 [INFO] Processed 222 records so far...
2025-01-29 10:25:15,807 [INFO] Email sent successfully with the CSV attachment.
2025-01-29 10:25:15,809 [INFO] Task completed: {"message": "Misused sender IDs have been processed and emailed successfully."}
Device set to use cpu
2025-01-29 10:30:12,492 [INFO] Django environment set up successfully.
2025-01-29 10:36:56,682 [INFO] Processed 220 records so far...
2025-01-29 10:37:01,547 [INFO] Email sent successfully with the CSV attachment.
2025-01-29 10:37:01,549 [INFO] Task completed: {"message": "Misused sender IDs have been processed and emailed successfully."}

Device set to use cpu
Traceback (most recent call last):
  File "/home/eduin/Desktop/message_classification/run_daily.py", line 11, in <module>
    logging.FileHandler("/app/daily_task.log"),
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/app/daily_task.log'
